[build]
  functions = "./functions"
  environment = { NODE_OPTIONS = "--openssl-legacy-provider" }

[[redirects]]
  from = '/api/clients'
  to = '/.netlify/functions/prismic-get-client-doc'
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  